export const commonWords = [
    { german: 'ich', english: 'I' },
  { german: 'du', english: 'you' },
  { german: 'er', english: 'he' },
  { german: 'sie', english: 'she/they' },
  { german: 'es', english: 'it' },
  { german: 'wir', english: 'we' },
  { german: 'ihr', english: 'you (plural)' },
  { german: 'und', english: 'and' },
  { german: 'oder', english: 'or' },
  { german: 'aber', english: 'but' },
  { german: 'ja', english: 'yes' },
  { german: 'nein', english: 'no' },
  { german: 'bitte', english: 'please' },
  { german: 'danke', english: 'thank you' },
  { german: 'gut', english: 'good' },
  { german: 'schlecht', english: 'bad' },
  { german: 'heute', english: 'today' },
  { german: 'morgen', english: 'tomorrow' },
  { german: 'gestern', english: 'yesterday' },
  { german: 'essen', english: 'to eat' },
  { german: 'trinken', english: 'to drink' },
  { german: 'sprechen', english: 'to speak' },
  { german: 'sehen', english: 'to see' },
  { german: 'gehen', english: 'to go' },
  { german: 'kommen', english: 'to come' },
];